export interface ToolInfo {
  slug: string;
  name: string;
  shortName: string;
  description: string;
  category: string;
  categorySlug: string;
  icon: string;
  keywords: string[];
  relatedTools: string[];
}

export const categories = [
  { slug: 'advertising', name: 'Advertising & Marketing ROI', icon: '📊' },
  { slug: 'freelance', name: 'Freelance & Business', icon: '💼' },
  { slug: 'seo', name: 'SEO & Site Analysis', icon: '🔍' },
  { slug: 'ai', name: 'AI & LLM Tools', icon: '🤖' },
] as const;

export const tools: ToolInfo[] = [
  // Category A: Advertising & Marketing ROI
  {
    slug: 'roas-calculator',
    name: 'ROAS Calculator',
    shortName: 'ROAS',
    description: 'Calculate Return on Ad Spend across multiple scenarios. Compare channels, adjust budgets, and see your profitability in real time.',
    category: 'Advertising & Marketing ROI',
    categorySlug: 'advertising',
    icon: '📊',
    keywords: ['roas', 'return on ad spend', 'advertising roi', 'ad performance'],
    relatedTools: ['cpc-cpm-cpa-converter', 'ad-budget-planner', 'landing-page-estimator'],
  },
  {
    slug: 'cpc-cpm-cpa-converter',
    name: 'CPC/CPM/CPA Converter',
    shortName: 'CPC/CPM/CPA',
    description: 'Convert between CPC, CPM, and CPA metrics instantly. Understand your true cost per acquisition across different pricing models.',
    category: 'Advertising & Marketing ROI',
    categorySlug: 'advertising',
    icon: '🔄',
    keywords: ['cpc', 'cpm', 'cpa', 'cost per click', 'cost per mille', 'cost per acquisition'],
    relatedTools: ['roas-calculator', 'ad-budget-planner', 'landing-page-estimator'],
  },
  {
    slug: 'ab-test-calculator',
    name: 'A/B Test Sample Size Calculator',
    shortName: 'A/B Test',
    description: 'Calculate the sample size needed for statistically significant A/B tests. Avoid premature conclusions with proper test planning.',
    category: 'Advertising & Marketing ROI',
    categorySlug: 'advertising',
    icon: '🧪',
    keywords: ['ab test', 'sample size', 'statistical significance', 'split test', 'experiment'],
    relatedTools: ['landing-page-estimator', 'roas-calculator', 'email-roi-calculator'],
  },
  {
    slug: 'email-roi-calculator',
    name: 'Email ROI Calculator',
    shortName: 'Email ROI',
    description: 'Calculate the ROI of your email marketing campaigns. Factor in list size, open rates, click rates, and revenue per subscriber.',
    category: 'Advertising & Marketing ROI',
    categorySlug: 'advertising',
    icon: '📧',
    keywords: ['email marketing', 'email roi', 'newsletter', 'open rate', 'click rate'],
    relatedTools: ['newsletter-value-calculator', 'content-roi-calculator', 'roas-calculator'],
  },
  {
    slug: 'content-roi-calculator',
    name: 'Content ROI Calculator',
    shortName: 'Content ROI',
    description: 'Measure the return on your content marketing investment. Track costs vs. traffic value, leads, and revenue attribution.',
    category: 'Advertising & Marketing ROI',
    categorySlug: 'advertising',
    icon: '📝',
    keywords: ['content marketing', 'content roi', 'blog roi', 'content strategy'],
    relatedTools: ['seo-roi-calculator', 'traffic-value-calculator', 'email-roi-calculator'],
  },
  {
    slug: 'ad-budget-planner',
    name: 'Ad Budget Planner',
    shortName: 'Ad Budget',
    description: 'Plan your advertising budget across channels. Simulate different allocation strategies and forecast performance.',
    category: 'Advertising & Marketing ROI',
    categorySlug: 'advertising',
    icon: '💰',
    keywords: ['ad budget', 'media planning', 'budget allocation', 'campaign planning'],
    relatedTools: ['roas-calculator', 'cpc-cpm-cpa-converter', 'landing-page-estimator'],
  },
  {
    slug: 'landing-page-estimator',
    name: 'Landing Page Conversion Estimator',
    shortName: 'LP Conversion',
    description: 'Estimate landing page conversion rates and revenue. Simulate changes to traffic, conversion rate, and average order value.',
    category: 'Advertising & Marketing ROI',
    categorySlug: 'advertising',
    icon: '🎯',
    keywords: ['landing page', 'conversion rate', 'cro', 'optimization'],
    relatedTools: ['ab-test-calculator', 'roas-calculator', 'ad-budget-planner'],
  },
  // Category B: Freelance & Business
  {
    slug: 'freelance-rate-calculator',
    name: 'Freelance Rate Calculator',
    shortName: 'Freelance Rate',
    description: 'Calculate your ideal freelance rate based on expenses, desired income, and billable hours.',
    category: 'Freelance & Business',
    categorySlug: 'freelance',
    icon: '💼',
    keywords: ['freelance rate', 'hourly rate', 'pricing', 'freelancer'],
    relatedTools: ['client-profitability-calculator', 'saas-pricing-calculator', 'course-revenue-estimator'],
  },
  {
    slug: 'newsletter-value-calculator',
    name: 'Newsletter Subscriber Value Calculator',
    shortName: 'Newsletter Value',
    description: 'Calculate the lifetime value of each newsletter subscriber and optimize your growth strategy.',
    category: 'Freelance & Business',
    categorySlug: 'freelance',
    icon: '📰',
    keywords: ['newsletter', 'subscriber value', 'email list', 'ltv'],
    relatedTools: ['email-roi-calculator', 'podcast-revenue-calculator', 'course-revenue-estimator'],
  },
  {
    slug: 'influencer-pricing-calculator',
    name: 'Influencer Pricing Calculator',
    shortName: 'Influencer Pricing',
    description: 'Calculate fair pricing for influencer collaborations based on followers, engagement, and platform.',
    category: 'Freelance & Business',
    categorySlug: 'freelance',
    icon: '⭐',
    keywords: ['influencer', 'pricing', 'sponsorship', 'collaboration'],
    relatedTools: ['podcast-revenue-calculator', 'content-roi-calculator', 'roas-calculator'],
  },
  {
    slug: 'saas-pricing-calculator',
    name: 'SaaS Pricing Calculator',
    shortName: 'SaaS Pricing',
    description: 'Model SaaS pricing strategies, churn impact, and LTV:CAC ratios across different price points.',
    category: 'Freelance & Business',
    categorySlug: 'freelance',
    icon: '🔧',
    keywords: ['saas', 'pricing', 'subscription', 'mrr', 'churn', 'ltv'],
    relatedTools: ['ai-saas-margin-calculator', 'client-profitability-calculator', 'freelance-rate-calculator'],
  },
  {
    slug: 'client-profitability-calculator',
    name: 'Client Profitability Calculator',
    shortName: 'Client Profit',
    description: 'Analyze profitability per client. Track revenue, costs, and time investment to identify your best clients.',
    category: 'Freelance & Business',
    categorySlug: 'freelance',
    icon: '📋',
    keywords: ['client profitability', 'project profitability', 'margin', 'agency'],
    relatedTools: ['freelance-rate-calculator', 'content-roi-calculator', 'saas-pricing-calculator'],
  },
  {
    slug: 'podcast-revenue-calculator',
    name: 'Podcast Revenue Calculator',
    shortName: 'Podcast Revenue',
    description: 'Estimate podcast revenue from sponsorships, ads, and premium content based on download numbers.',
    category: 'Freelance & Business',
    categorySlug: 'freelance',
    icon: '🎙️',
    keywords: ['podcast', 'revenue', 'sponsorship', 'downloads', 'cpm'],
    relatedTools: ['newsletter-value-calculator', 'influencer-pricing-calculator', 'course-revenue-estimator'],
  },
  {
    slug: 'course-revenue-estimator',
    name: 'Course Launch Revenue Estimator',
    shortName: 'Course Revenue',
    description: 'Estimate revenue from online course launches. Model pricing, conversion funnels, and launch strategies.',
    category: 'Freelance & Business',
    categorySlug: 'freelance',
    icon: '🎓',
    keywords: ['course', 'launch', 'revenue', 'online education', 'digital product'],
    relatedTools: ['newsletter-value-calculator', 'email-roi-calculator', 'landing-page-estimator'],
  },
  // Category C: SEO & Site Analysis
  {
    slug: 'seo-roi-calculator',
    name: 'SEO ROI Calculator',
    shortName: 'SEO ROI',
    description: 'Calculate the return on your SEO investment over time.',
    category: 'SEO & Site Analysis',
    categorySlug: 'seo',
    icon: '🔍',
    keywords: ['seo roi', 'organic search', 'seo investment'],
    relatedTools: ['traffic-value-calculator', 'da-impact-calculator', 'keyword-difficulty-estimator'],
  },
  {
    slug: 'da-impact-calculator',
    name: 'Domain Authority Impact Calculator',
    shortName: 'DA Impact',
    description: 'Estimate how Domain Authority changes impact your rankings and organic traffic.',
    category: 'SEO & Site Analysis',
    categorySlug: 'seo',
    icon: '🏛️',
    keywords: ['domain authority', 'da', 'rankings', 'organic traffic'],
    relatedTools: ['seo-roi-calculator', 'backlink-value-calculator', 'keyword-difficulty-estimator'],
  },
  {
    slug: 'traffic-value-calculator',
    name: 'Blog Traffic Value Calculator',
    shortName: 'Traffic Value',
    description: 'Calculate the monetary value of your organic blog traffic.',
    category: 'SEO & Site Analysis',
    categorySlug: 'seo',
    icon: '📈',
    keywords: ['traffic value', 'blog traffic', 'organic value'],
    relatedTools: ['seo-roi-calculator', 'content-roi-calculator', 'ad-revenue-calculator'],
  },
  {
    slug: 'keyword-difficulty-estimator',
    name: 'Keyword Difficulty Estimator',
    shortName: 'KD Estimator',
    description: 'Estimate keyword difficulty and resources needed to rank.',
    category: 'SEO & Site Analysis',
    categorySlug: 'seo',
    icon: '🔑',
    keywords: ['keyword difficulty', 'keyword research', 'seo difficulty'],
    relatedTools: ['seo-roi-calculator', 'da-impact-calculator', 'backlink-value-calculator'],
  },
  {
    slug: 'backlink-value-calculator',
    name: 'Backlink Value Calculator',
    shortName: 'Backlink Value',
    description: 'Calculate the value of backlinks based on referring domain authority and relevance.',
    category: 'SEO & Site Analysis',
    categorySlug: 'seo',
    icon: '🔗',
    keywords: ['backlink', 'link building', 'link value'],
    relatedTools: ['da-impact-calculator', 'seo-roi-calculator', 'keyword-difficulty-estimator'],
  },
  {
    slug: 'ad-revenue-calculator',
    name: 'Website Ad Revenue Calculator',
    shortName: 'Ad Revenue',
    description: 'Estimate ad revenue from display ads based on traffic and RPM.',
    category: 'SEO & Site Analysis',
    categorySlug: 'seo',
    icon: '💵',
    keywords: ['ad revenue', 'display ads', 'rpm', 'adsense'],
    relatedTools: ['traffic-value-calculator', 'content-roi-calculator', 'podcast-revenue-calculator'],
  },
  // Category D: AI & LLM Tools
  {
    slug: 'llm-pricing-calculator',
    name: 'LLM API Pricing Calculator',
    shortName: 'LLM Pricing',
    description: 'Compare API costs across LLM providers.',
    category: 'AI & LLM Tools',
    categorySlug: 'ai',
    icon: '🤖',
    keywords: ['llm', 'api pricing', 'openai', 'anthropic', 'google'],
    relatedTools: ['ai-agent-cost-estimator', 'token-counter', 'llm-comparison'],
  },
  {
    slug: 'ai-agent-cost-estimator',
    name: 'AI Agent Cost Estimator',
    shortName: 'Agent Cost',
    description: 'Estimate the cost of running AI agents in production.',
    category: 'AI & LLM Tools',
    categorySlug: 'ai',
    icon: '🕹️',
    keywords: ['ai agent', 'cost', 'automation', 'llm cost'],
    relatedTools: ['llm-pricing-calculator', 'rag-cost-calculator', 'ai-saas-margin-calculator'],
  },
  {
    slug: 'token-counter',
    name: 'Token Counter & Estimator',
    shortName: 'Token Counter',
    description: 'Count and estimate token usage for LLM API calls.',
    category: 'AI & LLM Tools',
    categorySlug: 'ai',
    icon: '🔢',
    keywords: ['token counter', 'tokenizer', 'token estimation'],
    relatedTools: ['llm-pricing-calculator', 'llm-comparison', 'ai-agent-cost-estimator'],
  },
  {
    slug: 'llm-comparison',
    name: 'Claude vs ChatGPT vs Gemini Comparison Tool',
    shortName: 'LLM Compare',
    description: 'Compare features, pricing, and capabilities across major LLM providers.',
    category: 'AI & LLM Tools',
    categorySlug: 'ai',
    icon: '⚖️',
    keywords: ['llm comparison', 'claude', 'chatgpt', 'gemini', 'model comparison'],
    relatedTools: ['llm-pricing-calculator', 'token-counter', 'ai-agent-cost-estimator'],
  },
  {
    slug: 'rag-cost-calculator',
    name: 'RAG Cost Calculator',
    shortName: 'RAG Cost',
    description: 'Calculate the cost of building and running RAG pipelines.',
    category: 'AI & LLM Tools',
    categorySlug: 'ai',
    icon: '📚',
    keywords: ['rag', 'retrieval augmented generation', 'embedding', 'vector db'],
    relatedTools: ['llm-pricing-calculator', 'ai-agent-cost-estimator', 'ai-saas-margin-calculator'],
  },
  {
    slug: 'ai-saas-margin-calculator',
    name: 'AI SaaS Margin Calculator',
    shortName: 'AI SaaS Margin',
    description: 'Calculate margins for AI-powered SaaS products factoring in LLM API costs.',
    category: 'AI & LLM Tools',
    categorySlug: 'ai',
    icon: '📊',
    keywords: ['ai saas', 'margin', 'llm cost', 'saas profitability'],
    relatedTools: ['saas-pricing-calculator', 'llm-pricing-calculator', 'rag-cost-calculator'],
  },
];

export function getToolBySlug(slug: string): ToolInfo | undefined {
  return tools.find(t => t.slug === slug);
}

export function getToolsByCategory(categorySlug: string): ToolInfo[] {
  return tools.filter(t => t.categorySlug === categorySlug);
}

export function getRelatedTools(slug: string): ToolInfo[] {
  const tool = getToolBySlug(slug);
  if (!tool) return [];
  return tool.relatedTools
    .map(s => getToolBySlug(s))
    .filter((t): t is ToolInfo => t !== undefined);
}
